In [91]:
import numpy as np
import sklearn
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
X, y = load_iris(return_X_y=True)
print(X[0:4,])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


In [92]:
# Scaling
# Learning the scaler
scaler = sklearn.preprocessing.StandardScaler().fit(X)
X = scaler.transform(X)
print(X[0:4,])
np.mean(X, axis=0) #Close to zero
np.std(X, axis=0)  #Close to one

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]]


array([1., 1., 1., 1.])

In [72]:
scaler = sklearn.preprocessing.StandardScaler().fit(X)
#X = scaler.transform(X)
clf = LogisticRegression().fit(X, y)
clf.predict(X[:2, :])
res = clf.predict_proba(X)
print('Res   ', res[0:3,])
print('Score ', clf.score(X, y))
y

Res    [[9.81807539e-01 1.81924463e-02 1.43689123e-08]
 [9.71738778e-01 2.82611920e-02 3.00562236e-08]
 [9.85456689e-01 1.45432984e-02 1.22790722e-08]]
Score  0.9733333333333334


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:939: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html.
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Calculation of the score by hand.

In [61]:
-np.mean(np.log(res[0:50,0])) - np.mean(np.log(res)[50:100,1]) - np.mean(np.log(res)[100:150,2])

0.35835962650406084

In [66]:
#np.mean(-np.log(res[0:50,0])) + 
np.mean(-np.log(res[50:100,1]))

0.18113877676634163

In [69]:
-np.log(res[50:100,1])

array([0.13428278, 0.15093783, 0.32070415, 0.06265333, 0.20489844,
       0.15064193, 0.33247853, 0.16329597, 0.109015  , 0.0922828 ,
       0.06437053, 0.10685854, 0.02383354, 0.24917122, 0.08862545,
       0.07649423, 0.25527375, 0.03536469, 0.22414756, 0.04143728,
       0.82041513, 0.04428591, 0.51869405, 0.15057505, 0.05880001,
       0.08334913, 0.2213208 , 0.731664  , 0.20726465, 0.06733656,
       0.04374666, 0.04571933, 0.04452075, 1.05108278, 0.28636271,
       0.2366843 , 0.21645362, 0.0915412 , 0.07399555, 0.06417578,
       0.10780791, 0.18816958, 0.04403101, 0.13324443, 0.08303681,
       0.06368937, 0.07746382, 0.06711835, 0.28146885, 0.06615319])

In [70]:
clf

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)